[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sigagent-sdk"
version = "0.1.5"
description = "SDK for interacting with the SigAgent API"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache-2.0" }
authors = [
    { name = "Analytiq" }
]
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.0.0",
]

[project.urls]
Repository = "https://github.com/analytiq/doc-router"

[tool.hatch.build.targets.wheel]
packages = ["src/sigagent_sdk"]
include = ["src/sigagent_sdk/py.typed"]
exclude = ["tests/**", "examples/**"]

[tool.hatch.build.targets.sdist]
exclude = [
  "dist/**",
  "build/**",
  "*.egg-info/**",
  ".venv*/**",
] 